# Generated by Django 5.0.7 on 2024-08-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControleDeIrrigacao',
        ),
    ]
