# Generated by Django 5.1 on 2024-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='46433-971', max_length=9),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='distrito',
            field=models.CharField(default='Ceraíma', max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='Bahia', max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.CharField(default='Guanambi', max_length=255),
        ),
    ]
