# Generated by Django 5.1 on 2024-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledeirrigacao',
            name='tolerancia_tempo',
            field=models.BigIntegerField(default=0),
        ),
    ]
