# Generated by Django 5.0.7 on 2024-07-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.BigIntegerField()),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDeConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DurationField()),
                ('modelo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FaturaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('periodo', models.DateField()),
                ('dataDeEmissao', models.DateField()),
                ('dataDeVencimento', models.DateField()),
                ('consumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumo_agua.consumo')),
            ],
        ),
    ]
