# Generated by Django 5.0.7 on 2024-07-10 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumo_agua', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaagua',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='relatoriodeconsumo',
            name='consumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='consumo_agua.consumo'),
        ),
    ]
